name: 'GitHub Actions Birthday Reminder'

on:
  push:	
    branches: [ master ]
  schedule:
    - cron: '1 0 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 'Install NPM dependencies'
        run: npm --registry https://registry.npm.taobao.org install request
      - name: 'Run code'
        run: node birthday.js
        env:
          DATA: ${{ secrets.DATA }}
          CORPID: ${{ secrets.CORPID }}
          SECRET: ${{ secrets.SECRET }}
          AGENTID: ${{ secrets.AGENTID }}
